g_SERVER_TICK_RATE = 3 -- ticks per second, limited by other things
g_DEBUG_MODE = true

g_SECRET_ENDING_REQUIREMENT_MULTIPLIER = 1.5
g_AVAILABLE_JOBS_MULTIPLIER = 3
g_DELAY_BETWEEN_JOB_SPAWN = 2000 -- milliseconds
g_DELAY_BETWEEN_EXIT_SPAWN = 15000 -- milliseconds
g_MAX_DELIVERY_BONUS = 2 -- compared to 1 for job
g_CRIME_REPORT_CHANCE = 0.25
g_CRIMINALS_PER_COP = 8