-- car = nil

-- function aaa(thePlayer, seat, jacked)
	-- if (getElementType(thePlayer) ~= "player") then
		-- return
	-- end
	-- -- asdf = getModelHandling(476)
	-- -- for k,g in pairs(asdf) do
		-- -- setVehicleHandling(source, k, g)
	-- -- end
	-- local sir = createPed(120,0,0,0)
	-- if (car) then
		-- destroyElement(car)
	-- end
	-- car = createVehicle(476,0,0,0)
	-- warpPedIntoVehicle(sir, car)
	-- attachElements(car,source,0,0,1,13,0,0)
		-- setElementAlpha(thePlayer, 0)
		-- setTimer(function(source)
		-- setElementAlpha(source, 0)

	-- end, 1000, 10, source)
-- end
-- addEventHandler("onVehicleEnter", root, aaa)